name: Thinkfast
favicon: null
layout_spectrum: 0.5550331976264715
typography_spectrum: 0.1709220374468714
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.2607319669332355
  lightness: 0.31083549931645393
  saturation: 0.7145735318772495
  rhythmicContrast: 0.40768348309211433
purpose: []
