name: Thinkfast
favicon: null
layout_spectrum: 0.5550331976264715
typography_spectrum: 0.75106
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-50059003-2
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#090518'
    - '#282191'
    - '#87218a'
    - '#5574f0'
    - '#b5aef9'
  brandStrength: 0.75
  lightness: 0.31083549931645393
  saturation: 0.7145735318772495
  rhythmicContrast: 0.40768348309211433
purpose: []
